apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: registration-service
  name: registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - image: nimbleplatform/registration-service:IMAGE_TAG
        imagePullPolicy: Always
        name: registration-service
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi